/* Generated by AN DISI Unibo */ 
package it.unibo.ctxRadarTfCe16;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.system.SituatedSysKb;
public class MainCtxRadarTfCe16  {
  
//MAIN
public static QActorContext initTheContext() throws Exception{
	IOutputEnvView outEnvView = SituatedSysKb.standardOutEnvView;
	it.unibo.is.interfaces.IBasicEnvAwt env=new it.unibo.baseEnv.basicFrame.EnvFrame( 
		"Env_ctxRadarTfCe16",java.awt.Color.cyan , java.awt.Color.black );
	env.init();
	outEnvView = env.getOutputEnvView();
	String webDir = "./srcMore/it/unibo/ctxRadarTfCe16";
	return QActorContext.initQActorSystem(
		"ctxradartfce16", "./srcMore/it/unibo/ctxRadarTfCe16/radar_gui.pl", 
		"./srcMore/it/unibo/ctxRadarTfCe16/sysRules.pl", outEnvView,webDir,false);
}
public static void main(String[] args) throws Exception{
	initTheContext();
} 	
}
