/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.radargui;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Radargui extends AbstractRadargui { 
	public Radargui(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
}
