/* Generated by AN DISI Unibo */ 
package it.unibo.ctxSensorEmitter;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.system.SituatedSysKb;
public class MainCtxSensorEmitter  {
  
//MAIN
public static QActorContext initTheContext() throws Exception{
	IOutputEnvView outEnvView = SituatedSysKb.standardOutEnvView;
	String webDir = null;
	return QActorContext.initQActorSystem(
		"ctxsensoremitter", "./srcMore/it/unibo/ctxSensorEmitter/radar_gui.pl", 
		"./srcMore/it/unibo/ctxSensorEmitter/sysRules.pl", outEnvView,webDir,false);
}
public static void main(String[] args) throws Exception{
	initTheContext();
} 	
}
