/* Generated by AN DISI Unibo */ 
package it.unibo.avatar;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

//
public class Avatar extends AbstractAvatar { 
	public Avatar(String actorId, QActorContext myCtx, IOutputEnvView outEnvView ) throws Exception{
		super(actorId,myCtx,outEnvView ,it.unibo.qactors.QActorUtils.robotBase );
	}
	
	public void action(){
		System.out.println("I'm in the action");
	}
}
